name: Lighthouse Audits

on:
  push:
    branches:
    - master
    - gh-pages
    - audits-action 

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Audit live URL
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://teomrd.github.io/miropad/'
    - name: Upload results as an artifact
      uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
